config/routes.rb
Digitalgoods::Application.routes.draw do
  resources :app_instances

  resources :parent_apps

  devise_for :users
  resources :goods

  resources :users

  root 'home#index'

end

app/models/app_instance.rb
# == Schema Information
#
# Table name: app_instances
#
#  id                :integer          not null, primary key
#  parent_app_id     :integer
#  unique_identifier :integer
#  user_id           :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class AppInstance < ActiveRecord::Base
  belongs_to :parent_app
  belongs_to :user
end

app/models/good.rb
# == Schema Information
#
# Table name: goods
#
#  id              :integer          not null, primary key
#  name            :text
#  app_instance_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#  description     :text
#  user_id         :integer
#

class Good < ActiveRecord::Base
  belongs_to :user
  belongs_to :parent_app
  belongs_to :app_instance
end

app/models/parent_app.rb
# == Schema Information
#
# Table name: parent_apps
#
#  id         :integer          not null, primary key
#  name       :text
#  created_at :datetime
#  updated_at :datetime
#

class ParentApp < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :goods
end

app/controllers/app_instances_controller.rb
class AppInstancesController < ApplicationController
  before_action :set_app_instance, only: [:show, :edit, :update, :destroy]

  # GET /app_instances
  # GET /app_instances.json
  def index
    @app_instances = AppInstance.all
  end

  # GET /app_instances/1
  # GET /app_instances/1.json
  def show
  end

  # GET /app_instances/new
  def new
    @app_instance = AppInstance.new
  end

  # GET /app_instances/1/edit
  def edit
  end

  # POST /app_instances
  # POST /app_instances.json
  def create
    @app_instance = AppInstance.new(app_instance_params)

    respond_to do |format|
      if @app_instance.save
        format.html { redirect_to @app_instance, notice: 'App instance was successfully created.' }
        format.json { render action: 'show', status: :created, location: @app_instance }
      else
        format.html { render action: 'new' }
        format.json { render json: @app_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_instances/1
  # PATCH/PUT /app_instances/1.json
  def update
    respond_to do |format|
      if @app_instance.update(app_instance_params)
        format.html { redirect_to @app_instance, notice: 'App instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @app_instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_instances/1
  # DELETE /app_instances/1.json
  def destroy
    @app_instance.destroy
    respond_to do |format|
      format.html { redirect_to app_instances_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_instance
      @app_instance = AppInstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_instance_params
      params.require(:app_instance).permit(:parent_app_id, :unique_identifier, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_good, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /goods
  # GET /goods.json
  def index
    @goods = Good.all
  end

  # GET /goods/1
  # GET /goods/1.json
  def show

  end

  # GET /goods/new
  def new
    @good = Good.new
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to @good, notice: 'Good was successfully created.' }
        format.json { render action: 'show', status: :created, location: @good }
        puts "YES"
      else
        format.html { render action: 'new' }
        format.json { render json: @good.errors.full_messages, status: :unprocessable_entity }
        puts "FUCK"
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to @good, notice: 'Good was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to goods_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:name, :type, :user_id, :parent_app_id, :app_instance_id, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
end

app/controllers/parent_apps_controller.rb
class ParentAppsController < ApplicationController
  before_action :set_parent_app, only: [:show, :edit, :update, :destroy]

  # GET /parent_apps
  # GET /parent_apps.json
  def index
    @parent_apps = ParentApp.all
  end

  # GET /parent_apps/1
  # GET /parent_apps/1.json
  def show
  end

  # GET /parent_apps/new
  def new
    @parent_app = ParentApp.new
  end

  # GET /parent_apps/1/edit
  def edit
  end

  # POST /parent_apps
  # POST /parent_apps.json
  def create
    @parent_app = ParentApp.new(parent_app_params)

    respond_to do |format|
      if @parent_app.save
        format.html { redirect_to @parent_app, notice: 'Parent app was successfully created.' }
        format.json { render action: 'show', status: :created, location: @parent_app }
      else
        format.html { render action: 'new' }
        format.json { render json: @parent_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parent_apps/1
  # PATCH/PUT /parent_apps/1.json
  def update
    respond_to do |format|
      if @parent_app.update(parent_app_params)
        format.html { redirect_to @parent_app, notice: 'Parent app was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parent_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parent_apps/1
  # DELETE /parent_apps/1.json
  def destroy
    @parent_app.destroy
    respond_to do |format|
      format.html { redirect_to parent_apps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent_app
      @parent_app = ParentApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_app_params
      params.require(:parent_app).permit(:name)
    end
end

app/helpers/app_instances_helper.rb
module AppInstancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parent_apps_helper.rb
module ParentAppsHelper
end

app/views/app_instances/_form.html.erb
<%= form_for(@app_instance) do |f| %>
  <% if @app_instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app_instance.errors.count, "error") %> prohibited this app_instance from being saved:</h2>

      <ul>
      <% @app_instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_app_id %><br>
    <%= f.text_field :parent_app_id %>
  </div>
  <div class="field">
    <%= f.label :unique_identifier %><br>
    <%= f.number_field :unique_identifier %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/app_instances/edit.html.erb
<h1>Editing app_instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @app_instance %> |
<%= link_to 'Back', app_instances_path %>

app/views/app_instances/index.html.erb
<h1>Listing app_instances</h1>

<table>
  <thead>
    <tr>
      <th>Parent app</th>
      <th>Unique identifier</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @app_instances.each do |app_instance| %>
      <tr>
        <td><%= app_instance.parent_app %></td>
        <td><%= app_instance.unique_identifier %></td>
        <td><%= app_instance.user %></td>
        <td><%= link_to 'Show', app_instance %></td>
        <td><%= link_to 'Edit', edit_app_instance_path(app_instance) %></td>
        <td><%= link_to 'Destroy', app_instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New App instance', new_app_instance_path %>

app/views/app_instances/new.html.erb
<h1>New app_instance</h1>

<%= render 'form' %>

<%= link_to 'Back', app_instances_path %>

app/views/app_instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Parent app:</strong>
  <%= @app_instance.parent_app %>
</p>

<p>
  <strong>Unique identifier:</strong>
  <%= @app_instance.unique_identifier %>
</p>

<p>
  <strong>User:</strong>
  <%= @app_instance.user %>
</p>

<%= link_to 'Edit', edit_app_instance_path(@app_instance) %> |
<%= link_to 'Back', app_instances_path %>

app/views/goods/_form.html.erb
<%= form_for(@good) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this good from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%#= f.label :parent_app_id %><br>
    <%#= f.text_field :parent_app_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :app_instance_id %><br>
    <%= f.text_field :app_instance_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/goods/edit.html.erb
<h1>Editing good</h1>

<%= render 'form' %>

<%= link_to 'Show', @good %> |
<%= link_to 'Back', goods_path %>

app/views/goods/index.html.erb
<h1>Listing goods</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th>Parent app</th>
      <th>App instance</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.id %></td>
        <td><%= good.name %></td>
        <td><%= good.description %></td>
        <td><%= good.user %></td>
        <td><%#= good.parent_app %></td>
        <td><%= good.app_instance %></td>
        <td><%= link_to 'Show', good %></td>
        <td><%= link_to 'Edit', edit_good_path(good) %></td>
        <td><%= link_to 'Destroy', good, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Good', new_good_path %>

app/views/goods/new.html.erb
<h1>New good</h1>

<%= render 'form' %>

<%= link_to 'Back', goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @good.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @good.description %>
<p>
  <strong>User:</strong>
  <%= @good.user.inspect %>
</p>

<p>
  <strong>Parent app:</strong>
  <%#= @good.parent_app %>
</p>

<p>
  <strong>App instance:</strong>
  <%= @good.app_instance.inspect %>
</p>

<%= link_to 'Edit', edit_good_path(@good) %> |
<%= link_to 'Back', goods_path %>

app/views/home/index.html.erb
<h1> lets get it </h1>
<strong><div> Digitial Goods! </div></strong>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Digitalgoods</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top navbar-inverse" role="navigation" >
  <div class="container">
  	<div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Digital Goods</a>
        </div>
    <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active">
            <li> <%= link_to "Home" , controller: "home" %>
            <li> <%= link_to "Goods" , goods_path %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top</a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div>
  </div>
</nav>
<%= yield %>

</body>
</html>

app/views/parent_apps/_form.html.erb
<%= form_for(@parent_app) do |f| %>
  <% if @parent_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent_app.errors.count, "error") %> prohibited this parent_app from being saved:</h2>

      <ul>
      <% @parent_app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parent_apps/edit.html.erb
<h1>Editing parent_app</h1>

<%= render 'form' %>

<%= link_to 'Show', @parent_app %> |
<%= link_to 'Back', parent_apps_path %>

app/views/parent_apps/index.html.erb
<h1>Listing parent_apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parent_apps.each do |parent_app| %>
      <tr>
        <td><%= parent_app.name %></td>
        <td><%= link_to 'Show', parent_app %></td>
        <td><%= link_to 'Edit', edit_parent_app_path(parent_app) %></td>
        <td><%= link_to 'Destroy', parent_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent app', new_parent_app_path %>

app/views/parent_apps/new.html.erb
<h1>New parent_app</h1>

<%= render 'form' %>

<%= link_to 'Back', parent_apps_path %>

app/views/parent_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent_app.name %>
</p>

<%= link_to 'Edit', edit_parent_app_path(@parent_app) %> |
<%= link_to 'Back', parent_apps_path %>